insert into  product(brand,gendertype,description,price) values ('Nike','It great for running','Women','800');
insert into  product(brand,gendertype,description,price) values ('Nike','It great for running','Men','1000');
insert into  product(brand,gendertype,description,price) values ('Adidas','When you want warmth','Men','900'); 
insert into  product(brand,gendertype,description,price) values ('Puma','When you want warmth','Men','1500'); 
insert into  product(brand,gendertype,description,price) values ('Ellese','Get the vibes going','Women','2000'); 
insert into  administrator(firstName,lastName,password,phone,username) values('Sabelo','Mlaba','sab11','0635586747','sab@gmail.com');
insert into  administrator(firstName,lastName,password,phone,username) values('Innocent','Khanyile','doc11','06584777254','doc@gmail.com');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Sanelisiwe','Mkhize','Adidas','Women','2021-08-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Lungelo','Hletshwayo','Nike','Men','2021-01-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Sanelisiwe','Mike','Puma','Men','2021-06-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Loren','Mkhize','Lacosta','Men','2021-05-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Philza','Navin','Adida','Women','2021-07-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Lesley','Smith','Nike','Women','2021-02-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Dorothy','Mkhize','Ellse','Women','2021-12-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Lesley','Navin','Grasshoper','Women','2021-12-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Sanelisiwe','Mkhize','Adidas','Women','2015-12-17','Female','06522584');
insert into users(name,lastname,brand,category,buying_date,gender,phone) values('Sanelisiwe','Mkhize','All star','Women','2015-12-17','Female','06522584');